server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/gb-db
    username: mus
    password: mus
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # TODO: удалить
        default_schema: public
        hbm2ddl:
          auto: validate
    show-sql: true
jwt:
  secret: secret
  lifetime: 30m
eureka:
  instance:
    appname: ${spring.application.name}
    instanceId: ${eureka.instance.appname}:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
