server:
  port: 8761
spring:
  application:
    name: task-manager-eureka-server
eureka:
  instance:
    appname: ${spring.application.name}
    instanceId: ${eureka.instance.appname}:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false

